# Generated by Django 3.2.15 on 2022-09-10 19:46

import bdeapp.utils.storage
import bdeapp.utils.validators
import django.core.validators
from django.db import migrations, models
import functools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier (UUID4)",
                        verbose_name="Uuid",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            bdeapp.utils.storage.uuid_path,
                            *(),
                            **{"from_instance": True, "suffix": "families/"}
                        ),
                        validators=[
                            django.core.validators.validate_image_file_extension,
                            bdeapp.utils.validators.ImageSizeValidator(500, 500),
                        ],
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family",
                "verbose_name_plural": "Families",
                "ordering": ["name"],
            },
        ),
    ]
