# Generated by Django 3.2.15 on 2022-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_alter_proof_proof_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_validations",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Maximum number of validations"
            ),
        ),
    ]
