# Generated by Django 3.2.15 on 2022-09-12 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_challenge_max_validations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="max_validations",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(limit_value=1)],
                verbose_name="Maximum number of validations",
            ),
        ),
    ]
