# Generated by Django 3.2.15 on 2022-10-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="facebook_link",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook link"),
        ),
        migrations.AddField(
            model_name="event",
            name="instagram_link",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram link"),
        ),
        migrations.AddField(
            model_name="event",
            name="maps_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Google Maps link"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="misc_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Miscellaneous link"
            ),
        ),
    ]
