# Generated by Django 3.2.15 on 2022-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_families",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Maximum number of families"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site configuration",
            },
        ),
    ]
