# Generated by Django 3.2.15 on 2022-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="max_proof_filesize",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Maximum proof file size (MB)"
            ),
        ),
    ]
