# Generated by Django 3.2.15 on 2022-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_siteconfiguration_max_proof_filesize"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_slug",
                    models.SlugField(
                        help_text="Your url will be accessible from <code>/to/url_name/</code>",
                        verbose_name="Url name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Url to redirect to", verbose_name="Redirect url"
                    ),
                ),
            ],
            options={
                "verbose_name": "Redirect link",
                "verbose_name_plural": "Redirect links",
            },
        ),
    ]
