# Generated by Django 3.2.15 on 2022-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_redirectlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirectlink",
            name="url_slug",
            field=models.SlugField(
                help_text="Your url will be accessible from <code>/to/url_name/</code>",
                unique=True,
                verbose_name="Url name",
            ),
        ),
    ]
