name: code-quality

on: [push]

jobs:
  isort:
    name: Check import sorting with isort
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: isort/isort-action@master
        with:
          requirementsFiles: requirements/dev.txt
          sortPaths: src

  black:
    name: Check code formatting with black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with: 
          src: ./src
